package com.zebone.dip.log.vo;

public class LogDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.ID_
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.DOC_NO
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String docNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.LOG_ID
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.EVENT_TYPE
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.ERROR_CODE
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.LOG_DETAILS
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String logDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOC_UPLOAD_LOG_DETAILS.EVENT_TIME
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    private String eventTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.ID_
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.ID_
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.ID_
     *
     * @param id the value for DOC_UPLOAD_LOG_DETAILS.ID_
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.DOC_NO
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.DOC_NO
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.DOC_NO
     *
     * @param docNo the value for DOC_UPLOAD_LOG_DETAILS.DOC_NO
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setDocNo(String docNo) {
        this.docNo = docNo == null ? null : docNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.LOG_ID
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.LOG_ID
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.LOG_ID
     *
     * @param logId the value for DOC_UPLOAD_LOG_DETAILS.LOG_ID
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.EVENT_TYPE
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.EVENT_TYPE
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.EVENT_TYPE
     *
     * @param eventType the value for DOC_UPLOAD_LOG_DETAILS.EVENT_TYPE
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.ERROR_CODE
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.ERROR_CODE
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.ERROR_CODE
     *
     * @param errorCode the value for DOC_UPLOAD_LOG_DETAILS.ERROR_CODE
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.LOG_DETAILS
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.LOG_DETAILS
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getLogDetails() {
        return logDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.LOG_DETAILS
     *
     * @param logDetails the value for DOC_UPLOAD_LOG_DETAILS.LOG_DETAILS
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setLogDetails(String logDetails) {
        this.logDetails = logDetails == null ? null : logDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOC_UPLOAD_LOG_DETAILS.EVENT_TIME
     *
     * @return the value of DOC_UPLOAD_LOG_DETAILS.EVENT_TIME
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public String getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOC_UPLOAD_LOG_DETAILS.EVENT_TIME
     *
     * @param eventTime the value for DOC_UPLOAD_LOG_DETAILS.EVENT_TIME
     *
     * @mbggenerated Tue Sep 10 08:34:04 CST 2013
     */
    public void setEventTime(String eventTime) {
        this.eventTime = eventTime == null ? null : eventTime.trim();
    }
}