package com.zebone.dip.metadata.vo;

public class DataSetConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DATASET_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DATASET_CONF.DATASET_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String datasetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DATASET_CONF.DATASET_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String datasetDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DATASET_CONF.STANDARD_CODE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String standardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DATASET_CONF.DATASET_VERSION
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String datasetVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DATASET_CONF.DATASET_CODE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String datasetCode;
    
    private String isDeleted;
    
    private String createTime;

    public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DATASET_CONF.ID_
     *
     * @return the value of P_DATASET_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DATASET_CONF.ID_
     *
     * @param id the value for P_DATASET_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DATASET_CONF.DATASET_NAME
     *
     * @return the value of P_DATASET_CONF.DATASET_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDatasetName() {
        return datasetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DATASET_CONF.DATASET_NAME
     *
     * @param datasetName the value for P_DATASET_CONF.DATASET_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName == null ? null : datasetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DATASET_CONF.DATASET_DESC
     *
     * @return the value of P_DATASET_CONF.DATASET_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDatasetDesc() {
        return datasetDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DATASET_CONF.DATASET_DESC
     *
     * @param datasetDesc the value for P_DATASET_CONF.DATASET_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDatasetDesc(String datasetDesc) {
        this.datasetDesc = datasetDesc == null ? null : datasetDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DATASET_CONF.STANDARD_CODE
     *
     * @return the value of P_DATASET_CONF.STANDARD_CODE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getStandardCode() {
        return standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DATASET_CONF.STANDARD_CODE
     *
     * @param standardCode the value for P_DATASET_CONF.STANDARD_CODE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setStandardCode(String standardCode) {
        this.standardCode = standardCode == null ? null : standardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DATASET_CONF.DATASET_VERSION
     *
     * @return the value of P_DATASET_CONF.DATASET_VERSION
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDatasetVersion() {
        return datasetVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DATASET_CONF.DATASET_VERSION
     *
     * @param datasetVersion the value for P_DATASET_CONF.DATASET_VERSION
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDatasetVersion(String datasetVersion) {
        this.datasetVersion = datasetVersion == null ? null : datasetVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DATASET_CONF.DATASET_CODE
     *
     * @return the value of P_DATASET_CONF.DATASET_CODE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDatasetCode() {
        return datasetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DATASET_CONF.DATASET_CODE
     *
     * @param datasetCode the value for P_DATASET_CONF.DATASET_CODE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDatasetCode(String datasetCode) {
        this.datasetCode = datasetCode == null ? null : datasetCode.trim();
    }
}