package com.zebone.dip.metadata.vo;

public class DocConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.DOC_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String docName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.DOC_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String docDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.DOC_VERSION
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String docVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.VERSION_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.DOC_TYPE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String docType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_CONF.DOC_XML
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String docXml;
    
    private String docXsd;
    
    private String isDeleted;
    
    private String createTime;
    
    private String docTypeCode;
    
    /**
     * 模型管理类型  1：文档模型2：注册模型
     */
    private String modelType;
    
    /**
     * 文档（实体）编码
     */
    private String docCode;
    
    /**
     * 版本类型
     */
    private String versionType;

    public String getDocTypeCode() {
		return docTypeCode;
	}

	public void setDocTypeCode(String docTypeCode) {
		this.docTypeCode = docTypeCode;
	}

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.ID_
     *
     * @return the value of P_DOC_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.ID_
     *
     * @param id the value for P_DOC_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.DOC_NAME
     *
     * @return the value of P_DOC_CONF.DOC_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.DOC_NAME
     *
     * @param docName the value for P_DOC_CONF.DOC_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.DOC_DESC
     *
     * @return the value of P_DOC_CONF.DOC_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDocDesc() {
        return docDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.DOC_DESC
     *
     * @param docDesc the value for P_DOC_CONF.DOC_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDocDesc(String docDesc) {
        this.docDesc = docDesc == null ? null : docDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.DOC_VERSION
     *
     * @return the value of P_DOC_CONF.DOC_VERSION
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDocVersion() {
        return docVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.DOC_VERSION
     *
     * @param docVersion the value for P_DOC_CONF.DOC_VERSION
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDocVersion(String docVersion) {
        this.docVersion = docVersion == null ? null : docVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.VERSION_NAME
     *
     * @return the value of P_DOC_CONF.VERSION_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.VERSION_NAME
     *
     * @param versionName the value for P_DOC_CONF.VERSION_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.DOC_TYPE
     *
     * @return the value of P_DOC_CONF.DOC_TYPE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDocType() {
        return docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.DOC_TYPE
     *
     * @param docType the value for P_DOC_CONF.DOC_TYPE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDocType(String docType) {
        this.docType = docType == null ? null : docType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_CONF.DOC_XML
     *
     * @return the value of P_DOC_CONF.DOC_XML
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getDocXml() {
        return docXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_CONF.DOC_XML
     *
     * @param docXml the value for P_DOC_CONF.DOC_XML
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setDocXml(String docXml) {
        this.docXml = docXml == null ? null : docXml.trim();
    }

	public String getDocXsd() {
		return docXsd;
	}

	public void setDocXsd(String docXsd) {
		this.docXsd = docXsd;
	}

	public String getModelType() {
		return modelType;
	}

	public void setModelType(String modelType) {
		this.modelType = modelType;
	}

	public String getDocCode() {
		return docCode;
	}

	public void setDocCode(String docCode) {
		this.docCode = docCode;
	}

	public String getVersionType() {
		return versionType;
	}

	public void setVersionType(String versionType) {
		this.versionType = versionType;
	}
    
    
}