package com.zebone.dip.metadata.vo;

/**
 * 文档数据映射
 * @author cz
 *
 */
public class DocMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.ID_
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
	/** 主键  **/
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.DOC_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 文档主键   **/
    private String docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.FIELD_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 数据源主键 **/
    private String fieldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.XPATH
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 节点的xpath **/
    private String xpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.CLOUMN_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 映射的列主键 id **/
    private String cloumnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.REPEAT
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 重复  **/
    private String repeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.IS_SELECT
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 可选  **/
    private String isSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING.IS_FEILD
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    /** 是否是元数据 **/
    private String isFeild;
    
    /** 函数   **/
    private String func;
    
    /** 组 **/
    private String groupNo;
    
    /** 唯一性 */
    private String isOnly;

    public String getIsOnly() {
		return isOnly;
	}

	public void setIsOnly(String isOnly) {
		this.isOnly = isOnly;
	}

	public String getFunc() {
		return func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.ID_
     *
     * @return the value of P_DOC_MAPPING.ID_
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.ID_
     *
     * @param id the value for P_DOC_MAPPING.ID_
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.DOC_ID
     *
     * @return the value of P_DOC_MAPPING.DOC_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.DOC_ID
     *
     * @param docId the value for P_DOC_MAPPING.DOC_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.FIELD_ID
     *
     * @return the value of P_DOC_MAPPING.FIELD_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.FIELD_ID
     *
     * @param fieldId the value for P_DOC_MAPPING.FIELD_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId == null ? null : fieldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.XPATH
     *
     * @return the value of P_DOC_MAPPING.XPATH
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getXpath() {
        return xpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.XPATH
     *
     * @param xpath the value for P_DOC_MAPPING.XPATH
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setXpath(String xpath) {
        this.xpath = xpath == null ? null : xpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.CLOUMN_ID
     *
     * @return the value of P_DOC_MAPPING.CLOUMN_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getCloumnId() {
        return cloumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.CLOUMN_ID
     *
     * @param cloumnId the value for P_DOC_MAPPING.CLOUMN_ID
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setCloumnId(String cloumnId) {
        this.cloumnId = cloumnId == null ? null : cloumnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.REPEAT
     *
     * @return the value of P_DOC_MAPPING.REPEAT
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getRepeat() {
        return repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.REPEAT
     *
     * @param repeat the value for P_DOC_MAPPING.REPEAT
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setRepeat(String repeat) {
        this.repeat = repeat == null ? null : repeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.IS_SELECT
     *
     * @return the value of P_DOC_MAPPING.IS_SELECT
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getIsSelect() {
        return isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.IS_SELECT
     *
     * @param isSelect the value for P_DOC_MAPPING.IS_SELECT
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setIsSelect(String isSelect) {
        this.isSelect = isSelect == null ? null : isSelect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING.IS_FEILD
     *
     * @return the value of P_DOC_MAPPING.IS_FEILD
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public String getIsFeild() {
        return isFeild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING.IS_FEILD
     *
     * @param isFeild the value for P_DOC_MAPPING.IS_FEILD
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    public void setIsFeild(String isFeild) {
        this.isFeild = isFeild == null ? null : isFeild.trim();
    }
    
    
	public String getGroupNo() {
		return groupNo;
	}

	public void setGroupNo(String groupNo) {
		this.groupNo = groupNo;
	}

	@Override
	public String toString() {
		return "DocMapping [id=" + id + ", docId=" + docId + ", fieldId="
				+ fieldId + ", xpath=" + xpath + ", cloumnId=" + cloumnId
				+ ", repeat=" + repeat + ", isSelect=" + isSelect
				+ ", isFeild=" + isFeild + ", func=" + func + "]";
	}
    
    
}