package com.zebone.dip.metadata.vo;

public class DocMap2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING2.ID_
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING2.MAPPING_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    private String mappingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING2.FIELD_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    private String fieldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING2.FUNCTION
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    private String function;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_DOC_MAPPING2.CLOUMN_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    private String cloumnId;
    
    
    private String sortMappingId; 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING2.ID_
     *
     * @return the value of P_DOC_MAPPING2.ID_
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING2.ID_
     *
     * @param id the value for P_DOC_MAPPING2.ID_
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING2.MAPPING_ID
     *
     * @return the value of P_DOC_MAPPING2.MAPPING_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public String getMappingId() {
        return mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING2.MAPPING_ID
     *
     * @param mappingId the value for P_DOC_MAPPING2.MAPPING_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public void setMappingId(String mappingId) {
        this.mappingId = mappingId == null ? null : mappingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING2.FIELD_ID
     *
     * @return the value of P_DOC_MAPPING2.FIELD_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING2.FIELD_ID
     *
     * @param fieldId the value for P_DOC_MAPPING2.FIELD_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId == null ? null : fieldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING2.FUNCTION
     *
     * @return the value of P_DOC_MAPPING2.FUNCTION
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING2.FUNCTION
     *
     * @param function the value for P_DOC_MAPPING2.FUNCTION
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_DOC_MAPPING2.CLOUMN_ID
     *
     * @return the value of P_DOC_MAPPING2.CLOUMN_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public String getCloumnId() {
        return cloumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_DOC_MAPPING2.CLOUMN_ID
     *
     * @param cloumnId the value for P_DOC_MAPPING2.CLOUMN_ID
     *
     * @mbggenerated Fri Jun 28 16:17:37 CST 2013
     */
    public void setCloumnId(String cloumnId) {
        this.cloumnId = cloumnId == null ? null : cloumnId.trim();
    }
    
    

	public String getSortMappingId() {
		return sortMappingId;
	}

	public void setSortMappingId(String sortMappingId) {
		this.sortMappingId = sortMappingId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DocMap2 [id=");
		builder.append(id);
		builder.append(", mappingId=");
		builder.append(mappingId);
		builder.append(", fieldId=");
		builder.append(fieldId);
		builder.append(", function=");
		builder.append(function);
		builder.append(", cloumnId=");
		builder.append(cloumnId);
		builder.append(", sortMappingId=");
		builder.append(sortMappingId);
		builder.append("]");
		return builder.toString();
	}
    
}