package com.zebone.dip.metadata.vo;

public class FieldColumnConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.TABLE_ID
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.COLUMN_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.COLUMN_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String columnDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.COLUMN_CONTENT
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String columnContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.COLUMN_LENGTH
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private Short columnLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.COLUMN_TYPE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.IS_NULL
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String isNull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.IS_KEY
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String isKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_FIELD_COLUMN_CONF.COLUMN_POLICY
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    private String columnPolicy;
    
    private String isDeleted;
    
    private String createTime;

    public String getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.ID_
     *
     * @return the value of P_FIELD_COLUMN_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.ID_
     *
     * @param id the value for P_FIELD_COLUMN_CONF.ID_
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.TABLE_ID
     *
     * @return the value of P_FIELD_COLUMN_CONF.TABLE_ID
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.TABLE_ID
     *
     * @param tableId the value for P_FIELD_COLUMN_CONF.TABLE_ID
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setTableId(String tableId) {
        this.tableId = tableId == null ? null : tableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.COLUMN_NAME
     *
     * @return the value of P_FIELD_COLUMN_CONF.COLUMN_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.COLUMN_NAME
     *
     * @param columnName the value for P_FIELD_COLUMN_CONF.COLUMN_NAME
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.COLUMN_DESC
     *
     * @return the value of P_FIELD_COLUMN_CONF.COLUMN_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getColumnDesc() {
        return columnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.COLUMN_DESC
     *
     * @param columnDesc the value for P_FIELD_COLUMN_CONF.COLUMN_DESC
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setColumnDesc(String columnDesc) {
        this.columnDesc = columnDesc == null ? null : columnDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.COLUMN_CONTENT
     *
     * @return the value of P_FIELD_COLUMN_CONF.COLUMN_CONTENT
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getColumnContent() {
        return columnContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.COLUMN_CONTENT
     *
     * @param columnContent the value for P_FIELD_COLUMN_CONF.COLUMN_CONTENT
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setColumnContent(String columnContent) {
        this.columnContent = columnContent == null ? null : columnContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.COLUMN_LENGTH
     *
     * @return the value of P_FIELD_COLUMN_CONF.COLUMN_LENGTH
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public Short getColumnLength() {
        return columnLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.COLUMN_LENGTH
     *
     * @param columnLength the value for P_FIELD_COLUMN_CONF.COLUMN_LENGTH
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setColumnLength(Short columnLength) {
        this.columnLength = columnLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.COLUMN_TYPE
     *
     * @return the value of P_FIELD_COLUMN_CONF.COLUMN_TYPE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.COLUMN_TYPE
     *
     * @param columnType the value for P_FIELD_COLUMN_CONF.COLUMN_TYPE
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType == null ? null : columnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.IS_NULL
     *
     * @return the value of P_FIELD_COLUMN_CONF.IS_NULL
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getIsNull() {
        return isNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.IS_NULL
     *
     * @param isNull the value for P_FIELD_COLUMN_CONF.IS_NULL
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setIsNull(String isNull) {
        this.isNull = isNull == null ? null : isNull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.IS_KEY
     *
     * @return the value of P_FIELD_COLUMN_CONF.IS_KEY
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getIsKey() {
        return isKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.IS_KEY
     *
     * @param isKey the value for P_FIELD_COLUMN_CONF.IS_KEY
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setIsKey(String isKey) {
        this.isKey = isKey == null ? null : isKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_FIELD_COLUMN_CONF.COLUMN_POLICY
     *
     * @return the value of P_FIELD_COLUMN_CONF.COLUMN_POLICY
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public String getColumnPolicy() {
        return columnPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_FIELD_COLUMN_CONF.COLUMN_POLICY
     *
     * @param columnPolicy the value for P_FIELD_COLUMN_CONF.COLUMN_POLICY
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    public void setColumnPolicy(String columnPolicy) {
        this.columnPolicy = columnPolicy == null ? null : columnPolicy.trim();
    }

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
    
    
}