package com.isell.ws.ningbo.ws.logistic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2015-11-03T19:20:08.892+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LogisticsWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LogisticsWebServiceSoap {

    @WebResult(name = "GetKJB2CLogisticsInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetKJB2CLogisticsInfo", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.logistic.GetKJB2CLogisticsInfo")
    @WebMethod(operationName = "GetKJB2CLogisticsInfo", action = "http://tempuri.org/GetKJB2CLogisticsInfo")
    @ResponseWrapper(localName = "GetKJB2CLogisticsInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.logistic.GetKJB2CLogisticsInfoResponse")
    public java.lang.String getKJB2CLogisticsInfo(
        @WebParam(name = "erpKey", targetNamespace = "http://tempuri.org/")
        java.lang.String erpKey,
        @WebParam(name = "erpSecret", targetNamespace = "http://tempuri.org/")
        java.lang.String erpSecret,
        @WebParam(name = "shopID", targetNamespace = "http://tempuri.org/")
        int shopID,
        @WebParam(name = "Tid", targetNamespace = "http://tempuri.org/")
        java.lang.String tid
    );

    @WebResult(name = "GetLogisticsMainResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLogisticsMain", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.logistic.GetLogisticsMain")
    @WebMethod(operationName = "GetLogisticsMain", action = "http://tempuri.org/GetLogisticsMain")
    @ResponseWrapper(localName = "GetLogisticsMainResponse", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.logistic.GetLogisticsMainResponse")
    public java.lang.String getLogisticsMain(
        @WebParam(name = "erpKey", targetNamespace = "http://tempuri.org/")
        java.lang.String erpKey,
        @WebParam(name = "erpSecret", targetNamespace = "http://tempuri.org/")
        java.lang.String erpSecret
    );

    @WebResult(name = "GetLogisticsInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLogisticsInfo", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.logistic.GetLogisticsInfo")
    @WebMethod(operationName = "GetLogisticsInfo", action = "http://tempuri.org/GetLogisticsInfo")
    @ResponseWrapper(localName = "GetLogisticsInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.logistic.GetLogisticsInfoResponse")
    public java.lang.String getLogisticsInfo(
        @WebParam(name = "erpKey", targetNamespace = "http://tempuri.org/")
        java.lang.String erpKey,
        @WebParam(name = "erpSecret", targetNamespace = "http://tempuri.org/")
        java.lang.String erpSecret,
        @WebParam(name = "shopID", targetNamespace = "http://tempuri.org/")
        int shopID,
        @WebParam(name = "Tid", targetNamespace = "http://tempuri.org/")
        java.lang.String tid
    );
}
