package com.zebone.empi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zebone.btp.core.mybatis.DcMapper;
import com.zebone.empi.vo.DocStorageLog;
import com.zebone.empi.vo.DocStorageLogExample;

@DcMapper
public interface DocStorageLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int countByExample(DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int deleteByExample(DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int insert(DocStorageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int insertSelective(DocStorageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    List<DocStorageLog> selectByExampleWithBLOBs(DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    List<DocStorageLog> selectByExample(DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    DocStorageLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") DocStorageLog record, @Param("example") DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") DocStorageLog record, @Param("example") DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int updateByExample(@Param("record") DocStorageLog record, @Param("example") DocStorageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int updateByPrimaryKeySelective(DocStorageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(DocStorageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table D_DOC_STORAGE_LOG
     *
     * @mbggenerated Wed Aug 13 08:46:09 CST 2014
     */
    int updateByPrimaryKey(DocStorageLog record);
}