package com.zebone.empi.dao;

import com.zebone.btp.core.mybatis.DipMapper;
import com.zebone.empi.vo.ParseTableLog;
import com.zebone.empi.vo.ParseTableLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@DipMapper
public interface ParseTableLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int countByExample(ParseTableLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int deleteByExample(ParseTableLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int insert(ParseTableLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int insertSelective(ParseTableLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    List<ParseTableLog> selectByExample(ParseTableLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    ParseTableLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int updateByExampleSelective(@Param("record") ParseTableLog record, @Param("example") ParseTableLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int updateByExample(@Param("record") ParseTableLog record, @Param("example") ParseTableLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int updateByPrimaryKeySelective(ParseTableLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_PARSE_TABLE_LOG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    int updateByPrimaryKey(ParseTableLog record);
}