package com.zebone.empi.dao;

import com.zebone.btp.core.mybatis.WrcMapper;
import com.zebone.empi.vo.RegisterMain;
import com.zebone.empi.vo.RegisterMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@WrcMapper
public interface RegisterMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int countByExample(RegisterMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int deleteByExample(RegisterMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int insert(RegisterMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int insertSelective(RegisterMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    List<RegisterMain> selectByExample(RegisterMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    RegisterMain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int updateByExampleSelective(@Param("record") RegisterMain record, @Param("example") RegisterMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int updateByExample(@Param("record") RegisterMain record, @Param("example") RegisterMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int updateByPrimaryKeySelective(RegisterMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_MAIN
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    int updateByPrimaryKey(RegisterMain record);
}