package com.zebone.dip.md.dao;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.md.vo.MasterData;

import java.util.List;

/**
 * @author Yang Ying
 * @version 2013-07-02
 */

@Mapper
public interface MasterDataMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MASTER_DATA
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MASTER_DATA
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    int insert(MasterData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MASTER_DATA
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    int insertSelective(MasterData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MASTER_DATA
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    MasterData selectByPrimaryKey(String id);
    
    /**
     * 根据主数据编码得到主数据信息
     * @param code
     * @return
     * @author songjunjie
     */
    MasterData getByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MASTER_DATA
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    int updateByPrimaryKeySelective(MasterData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MASTER_DATA
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    int updateByPrimaryKey(MasterData record);

    /**
     * 根据主数据类别ID，获取此类别下的所有主数据。
     * @param typeId 类别ID
     * @return 主数据列表
     */
    List<MasterData> getMasterDataByTypeId (String typeId);
    
    /**
     * 获取所有的masterdata
     * @return
     */
    List<MasterData> getAllMasterData();
}