package com.zebone.dip.ws.resource.dao;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.ws.resource.model.PResourceDeptInfo;
import com.zebone.dip.ws.resource.model.PResourceDeptInfoExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PResourceDeptInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int countByExample(PResourceDeptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int deleteByExample(PResourceDeptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int deleteByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int insert(PResourceDeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int insertSelective(PResourceDeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    List<PResourceDeptInfo> selectByExample(PResourceDeptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    PResourceDeptInfo selectByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int updateByExampleSelective(@Param("record") PResourceDeptInfo record, @Param("example") PResourceDeptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int updateByExample(@Param("record") PResourceDeptInfo record, @Param("example") PResourceDeptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int updateByPrimaryKeySelective(PResourceDeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_DEPT_INFO
     *
     * @mbggenerated Fri Mar 28 10:50:15 CST 2014
     */
    int updateByPrimaryKey(PResourceDeptInfo record);

    /**
     * 校验科室是否唯一
     * @param resourceDeptInfo
     * @return
     */
	int checkDeptUnique(PResourceDeptInfo resourceDeptInfo);
}