package com.zebone.dip.ws.resource.dao;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.ws.resource.model.PResourceFamilyLog;
import com.zebone.dip.ws.resource.model.PResourceFamilyLogExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PResourceFamilyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int countByExample(PResourceFamilyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByExample(PResourceFamilyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insert(PResourceFamilyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insertSelective(PResourceFamilyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    List<PResourceFamilyLog> selectByExample(PResourceFamilyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    PResourceFamilyLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") PResourceFamilyLog record, @Param("example") PResourceFamilyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExample(@Param("record") PResourceFamilyLog record, @Param("example") PResourceFamilyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKeySelective(PResourceFamilyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKey(PResourceFamilyLog record);
}