package com.zebone.dip.ws.resource.dao;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.ws.resource.model.PResourceFamilyMembers;
import com.zebone.dip.ws.resource.model.PResourceFamilyMembersExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PResourceFamilyMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int countByExample(PResourceFamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByExample(PResourceFamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insert(PResourceFamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insertSelective(PResourceFamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    List<PResourceFamilyMembers> selectByExample(PResourceFamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    PResourceFamilyMembers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") PResourceFamilyMembers record, @Param("example") PResourceFamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExample(@Param("record") PResourceFamilyMembers record, @Param("example") PResourceFamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKeySelective(PResourceFamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKey(PResourceFamilyMembers record);

	int insertList(List<PResourceFamilyMembers> resourceFamilyMembers);
}