package com.zebone.dip.ws.resource.dao;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.ws.resource.model.PResourceFamilyMembersLog;
import com.zebone.dip.ws.resource.model.PResourceFamilyMembersLogExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PResourceFamilyMembersLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int countByExample(PResourceFamilyMembersLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByExample(PResourceFamilyMembersLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insert(PResourceFamilyMembersLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insertSelective(PResourceFamilyMembersLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    List<PResourceFamilyMembersLog> selectByExample(PResourceFamilyMembersLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    PResourceFamilyMembersLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") PResourceFamilyMembersLog record, @Param("example") PResourceFamilyMembersLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExample(@Param("record") PResourceFamilyMembersLog record, @Param("example") PResourceFamilyMembersLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKeySelective(PResourceFamilyMembersLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS_LOG
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKey(PResourceFamilyMembersLog record);

	int insertList(List<PResourceFamilyMembersLog> resourceFamilyMembersLog);
}