package com.zebone.dip.ws.resource.dao;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.ws.resource.model.PResourceFamilyInfo;
import com.zebone.dip.ws.resource.model.PResourceFamilyInfoExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PResourceFamilyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int countByExample(PResourceFamilyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByExample(PResourceFamilyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int deleteByPrimaryKey(String famiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insert(PResourceFamilyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int insertSelective(PResourceFamilyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    List<PResourceFamilyInfo> selectByExample(PResourceFamilyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    PResourceFamilyInfo selectByPrimaryKey(String famiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") PResourceFamilyInfo record, @Param("example") PResourceFamilyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByExample(@Param("record") PResourceFamilyInfo record, @Param("example") PResourceFamilyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKeySelective(PResourceFamilyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_INFO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    int updateByPrimaryKey(PResourceFamilyInfo record);

    /**
     * 校验家庭是否唯一
     * @param resourceFamilyInfo
     * @return
     */
	int checkFamilyUnique(PResourceFamilyInfo resourceFamilyInfo);
}