package com.zebone.dip.md.vo;

/**
 * 主数据对象
 * @author Yang Ying
 * @version 2013-07-02
 */

public class MasterData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MASTER_DATA.ID_
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MASTER_DATA.CODE
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MASTER_DATA.NAME
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MASTER_DATA.TABLE_NAME
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MASTER_DATA.TYPE_ID
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MASTER_DATA.COMMENT
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MASTER_DATA.ID_
     *
     * @return the value of P_MASTER_DATA.ID_
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MASTER_DATA.ID_
     *
     * @param id the value for P_MASTER_DATA.ID_
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MASTER_DATA.CODE
     *
     * @return the value of P_MASTER_DATA.CODE
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MASTER_DATA.CODE
     *
     * @param code the value for P_MASTER_DATA.CODE
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MASTER_DATA.NAME
     *
     * @return the value of P_MASTER_DATA.NAME
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MASTER_DATA.NAME
     *
     * @param name the value for P_MASTER_DATA.NAME
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MASTER_DATA.TABLE_NAME
     *
     * @return the value of P_MASTER_DATA.TABLE_NAME
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MASTER_DATA.TABLE_NAME
     *
     * @param tableName the value for P_MASTER_DATA.TABLE_NAME
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MASTER_DATA.TYPE_ID
     *
     * @return the value of P_MASTER_DATA.TYPE_ID
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MASTER_DATA.TYPE_ID
     *
     * @param typeId the value for P_MASTER_DATA.TYPE_ID
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MASTER_DATA.COMMENT
     *
     * @return the value of P_MASTER_DATA.COMMENT
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MASTER_DATA.COMMENT
     *
     * @param comment the value for P_MASTER_DATA.COMMENT
     *
     * @mbggenerated Mon Jul 01 16:41:00 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}