package com.zebone.dip.metadata.dao;

import org.apache.ibatis.annotations.Param;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.metadata.vo.DatasetMapping;
@Mapper
public interface DatasetMappingMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_DATASET_MAPPING
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_DATASET_MAPPING
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    int insert(DatasetMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_DATASET_MAPPING
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    int insertSelective(DatasetMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_DATASET_MAPPING
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    DatasetMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_DATASET_MAPPING
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    int updateByPrimaryKeySelective(DatasetMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_DATASET_MAPPING
     *
     * @mbggenerated Fri Jun 28 08:34:54 CST 2013
     */
    int updateByPrimaryKey(DatasetMapping record);

	/**
	 * @author caixl
	 * @date Jun 28, 2013
	 * @description TODO 解除数据元与数据集的关系
	 * @param dd
	 * @return int
	 */
	int revokeMetadata(DatasetMapping dd);

	/**
	 * @author caixl
	 * @date Jun 28, 2013
	 * @description TODO 获取数据集的元数据个数
	 * @param datasetId
	 * @return int
	 */
	int getCountByDatasetId(@Param("datasetId")String datasetId);

	/**
	 * @author caixl
	 * @date Jul 26, 2013
	 * @description TODO 验证数据集中是否存在该元数据别名
	 * @param datasetMapping
	 * @return int
	 */
	int datasetExistsYsjbm(DatasetMapping datasetMapping);
}