package com.zebone.dip.metadata.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.zebone.btp.core.mybatis.Mapper;
import com.zebone.dip.metadata.vo.FieldTableConf;

@Mapper
public interface FieldTableConfMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_FIELD_TABLE_CONF
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_FIELD_TABLE_CONF
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    int insert(FieldTableConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_FIELD_TABLE_CONF
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    int insertSelective(FieldTableConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_FIELD_TABLE_CONF
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    FieldTableConf selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_FIELD_TABLE_CONF
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    int updateByPrimaryKeySelective(FieldTableConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_FIELD_TABLE_CONF
     *
     * @mbggenerated Tue Jun 25 14:45:52 CST 2013
     */
    int updateTableStruInfo(FieldTableConf record);

    //获取表结构信息列表
    List<FieldTableConf> tableSturList(RowBounds rowBounds, FieldTableConf fieldConf);

    //获取表结构信息总数
    int tableStruTotalCount(FieldTableConf fieldTableConf);

    //注册表结构信息
    int saveTableStruInfo(FieldTableConf fieldTableConf);

    //查看表所包含字段的个数
    int columnExistsDataSet (String id);

    //根据id删除表结构信息
    int deleteTableStruByIds (List<String> list);
    
    /**
     * 模糊查询所有的表名
     * @param tableDesc
     * @return
     */
    List<FieldTableConf> selectByLikeTableDesc(@Param(value="tableDesc") String tableDesc);

    /**
     * 判断该表名是否已经存在
     * @param fieldTableConf
     * @return
     */
    int countTableName(FieldTableConf fieldTableConf);
}