package com.isell.ws.ningbo.ws.stock;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StockSyncWebServiceSoap", targetNamespace = "http://tempuri.org/")
public interface StockSyncWebServiceSoap {

	/**
	 * 
	 * @param erpKey
	 * @param xml
	 * @param erpSecret
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetStock", action = "http://tempuri.org/GetStock")
	@WebResult(name = "GetStockResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetStock", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.stock.GetStock")
	@ResponseWrapper(localName = "GetStockResponse", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.stock.GetStockResponse")
	public String getStock(
			@WebParam(name = "erpKey", targetNamespace = "http://tempuri.org/") String erpKey,
			@WebParam(name = "erpSecret", targetNamespace = "http://tempuri.org/") String erpSecret,
			@WebParam(name = "xml", targetNamespace = "http://tempuri.org/") String xml);

	/**
	 * 
	 * @param erpKey
	 * @param xml
	 * @param erpSecret
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetAllStock", action = "http://tempuri.org/GetAllStock")
	@WebResult(name = "GetAllStockResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetAllStock", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.stock.GetAllStock")
	@ResponseWrapper(localName = "GetAllStockResponse", targetNamespace = "http://tempuri.org/", className = "com.isell.ws.ningbo.ws.stock.GetAllStockResponse")
	public String getAllStock(
			@WebParam(name = "erpKey", targetNamespace = "http://tempuri.org/") String erpKey,
			@WebParam(name = "erpSecret", targetNamespace = "http://tempuri.org/") String erpSecret,
			@WebParam(name = "xml", targetNamespace = "http://tempuri.org/") String xml);

}
