package com.zebone.empi.vo;

public class DocStorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.ID_
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.CREATE_TIME
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.EMPI_ID
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String empiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_OPER_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docOperState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_ORG
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_REGISTER_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docRegisterState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_TYPE_CODE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_NO
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_PARSE_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docParseState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_VERSION
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_DOC_STORAGE.DOC_XML
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    private String docXml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.ID_
     *
     * @return the value of D_DOC_STORAGE.ID_
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.ID_
     *
     * @param id the value for D_DOC_STORAGE.ID_
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.CREATE_TIME
     *
     * @return the value of D_DOC_STORAGE.CREATE_TIME
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.CREATE_TIME
     *
     * @param createTime the value for D_DOC_STORAGE.CREATE_TIME
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.EMPI_ID
     *
     * @return the value of D_DOC_STORAGE.EMPI_ID
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getEmpiId() {
        return empiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.EMPI_ID
     *
     * @param empiId the value for D_DOC_STORAGE.EMPI_ID
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setEmpiId(String empiId) {
        this.empiId = empiId == null ? null : empiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_OPER_STATE
     *
     * @return the value of D_DOC_STORAGE.DOC_OPER_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocOperState() {
        return docOperState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_OPER_STATE
     *
     * @param docOperState the value for D_DOC_STORAGE.DOC_OPER_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocOperState(String docOperState) {
        this.docOperState = docOperState == null ? null : docOperState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_ORG
     *
     * @return the value of D_DOC_STORAGE.DOC_ORG
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocOrg() {
        return docOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_ORG
     *
     * @param docOrg the value for D_DOC_STORAGE.DOC_ORG
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocOrg(String docOrg) {
        this.docOrg = docOrg == null ? null : docOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_REGISTER_STATE
     *
     * @return the value of D_DOC_STORAGE.DOC_REGISTER_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocRegisterState() {
        return docRegisterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_REGISTER_STATE
     *
     * @param docRegisterState the value for D_DOC_STORAGE.DOC_REGISTER_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocRegisterState(String docRegisterState) {
        this.docRegisterState = docRegisterState == null ? null : docRegisterState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_TYPE_CODE
     *
     * @return the value of D_DOC_STORAGE.DOC_TYPE_CODE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocTypeCode() {
        return docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_TYPE_CODE
     *
     * @param docTypeCode the value for D_DOC_STORAGE.DOC_TYPE_CODE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocTypeCode(String docTypeCode) {
        this.docTypeCode = docTypeCode == null ? null : docTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_NO
     *
     * @return the value of D_DOC_STORAGE.DOC_NO
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_NO
     *
     * @param docNo the value for D_DOC_STORAGE.DOC_NO
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocNo(String docNo) {
        this.docNo = docNo == null ? null : docNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_PARSE_STATE
     *
     * @return the value of D_DOC_STORAGE.DOC_PARSE_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocParseState() {
        return docParseState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_PARSE_STATE
     *
     * @param docParseState the value for D_DOC_STORAGE.DOC_PARSE_STATE
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocParseState(String docParseState) {
        this.docParseState = docParseState == null ? null : docParseState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_VERSION
     *
     * @return the value of D_DOC_STORAGE.DOC_VERSION
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocVersion() {
        return docVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_VERSION
     *
     * @param docVersion the value for D_DOC_STORAGE.DOC_VERSION
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocVersion(String docVersion) {
        this.docVersion = docVersion == null ? null : docVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_DOC_STORAGE.DOC_XML
     *
     * @return the value of D_DOC_STORAGE.DOC_XML
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public String getDocXml() {
        return docXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_DOC_STORAGE.DOC_XML
     *
     * @param docXml the value for D_DOC_STORAGE.DOC_XML
     *
     * @mbggenerated Wed Aug 06 12:08:13 CST 2014
     */
    public void setDocXml(String docXml) {
        this.docXml = docXml == null ? null : docXml.trim();
    }
}