package com.zebone.empi.vo;

public class ParseTableLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PARSE_TABLE_LOG.ID_
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PARSE_TABLE_LOG.CREATE_TIME
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PARSE_TABLE_LOG.TABLE_NAME
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PARSE_TABLE_LOG.EMPI_NO
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    private String empiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PARSE_TABLE_LOG.DOC_NO
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    private String docNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PARSE_TABLE_LOG.DATA_FLAG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    private String dataFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PARSE_TABLE_LOG.ID_
     *
     * @return the value of P_PARSE_TABLE_LOG.ID_
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PARSE_TABLE_LOG.ID_
     *
     * @param id the value for P_PARSE_TABLE_LOG.ID_
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PARSE_TABLE_LOG.CREATE_TIME
     *
     * @return the value of P_PARSE_TABLE_LOG.CREATE_TIME
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PARSE_TABLE_LOG.CREATE_TIME
     *
     * @param createTime the value for P_PARSE_TABLE_LOG.CREATE_TIME
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PARSE_TABLE_LOG.TABLE_NAME
     *
     * @return the value of P_PARSE_TABLE_LOG.TABLE_NAME
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PARSE_TABLE_LOG.TABLE_NAME
     *
     * @param tableName the value for P_PARSE_TABLE_LOG.TABLE_NAME
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PARSE_TABLE_LOG.EMPI_NO
     *
     * @return the value of P_PARSE_TABLE_LOG.EMPI_NO
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public String getEmpiNo() {
        return empiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PARSE_TABLE_LOG.EMPI_NO
     *
     * @param empiNo the value for P_PARSE_TABLE_LOG.EMPI_NO
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public void setEmpiNo(String empiNo) {
        this.empiNo = empiNo == null ? null : empiNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PARSE_TABLE_LOG.DOC_NO
     *
     * @return the value of P_PARSE_TABLE_LOG.DOC_NO
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PARSE_TABLE_LOG.DOC_NO
     *
     * @param docNo the value for P_PARSE_TABLE_LOG.DOC_NO
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public void setDocNo(String docNo) {
        this.docNo = docNo == null ? null : docNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PARSE_TABLE_LOG.DATA_FLAG
     *
     * @return the value of P_PARSE_TABLE_LOG.DATA_FLAG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PARSE_TABLE_LOG.DATA_FLAG
     *
     * @param dataFlag the value for P_PARSE_TABLE_LOG.DATA_FLAG
     *
     * @mbggenerated Wed Aug 13 13:22:49 CST 2014
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }
}