package com.zebone.empi.vo;

import com.zebone.btp.core.mybatis.WrcMapper;

@WrcMapper
public class RegisterLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.ID_
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.MAIN_ID
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String mainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.EMPI_ID
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String empiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_DATA_SOURCE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docDataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_ORG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_STATE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_OPER_STATE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docOperState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_TYPE_CODE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_NO
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_WEB_URL
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docWebUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.REGISTER_TIME
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_REGISTER_LOG.DOC_VERSION
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    private String docVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.ID_
     *
     * @return the value of R_REGISTER_LOG.ID_
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.ID_
     *
     * @param id the value for R_REGISTER_LOG.ID_
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.MAIN_ID
     *
     * @return the value of R_REGISTER_LOG.MAIN_ID
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.MAIN_ID
     *
     * @param mainId the value for R_REGISTER_LOG.MAIN_ID
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setMainId(String mainId) {
        this.mainId = mainId == null ? null : mainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.EMPI_ID
     *
     * @return the value of R_REGISTER_LOG.EMPI_ID
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getEmpiId() {
        return empiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.EMPI_ID
     *
     * @param empiId the value for R_REGISTER_LOG.EMPI_ID
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setEmpiId(String empiId) {
        this.empiId = empiId == null ? null : empiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_DATA_SOURCE
     *
     * @return the value of R_REGISTER_LOG.DOC_DATA_SOURCE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocDataSource() {
        return docDataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_DATA_SOURCE
     *
     * @param docDataSource the value for R_REGISTER_LOG.DOC_DATA_SOURCE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocDataSource(String docDataSource) {
        this.docDataSource = docDataSource == null ? null : docDataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_ORG
     *
     * @return the value of R_REGISTER_LOG.DOC_ORG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocOrg() {
        return docOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_ORG
     *
     * @param docOrg the value for R_REGISTER_LOG.DOC_ORG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocOrg(String docOrg) {
        this.docOrg = docOrg == null ? null : docOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_STATE
     *
     * @return the value of R_REGISTER_LOG.DOC_STATE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocState() {
        return docState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_STATE
     *
     * @param docState the value for R_REGISTER_LOG.DOC_STATE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocState(String docState) {
        this.docState = docState == null ? null : docState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_OPER_STATE
     *
     * @return the value of R_REGISTER_LOG.DOC_OPER_STATE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocOperState() {
        return docOperState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_OPER_STATE
     *
     * @param docOperState the value for R_REGISTER_LOG.DOC_OPER_STATE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocOperState(String docOperState) {
        this.docOperState = docOperState == null ? null : docOperState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_TYPE_CODE
     *
     * @return the value of R_REGISTER_LOG.DOC_TYPE_CODE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocTypeCode() {
        return docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_TYPE_CODE
     *
     * @param docTypeCode the value for R_REGISTER_LOG.DOC_TYPE_CODE
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocTypeCode(String docTypeCode) {
        this.docTypeCode = docTypeCode == null ? null : docTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_NO
     *
     * @return the value of R_REGISTER_LOG.DOC_NO
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_NO
     *
     * @param docNo the value for R_REGISTER_LOG.DOC_NO
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocNo(String docNo) {
        this.docNo = docNo == null ? null : docNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_WEB_URL
     *
     * @return the value of R_REGISTER_LOG.DOC_WEB_URL
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocWebUrl() {
        return docWebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_WEB_URL
     *
     * @param docWebUrl the value for R_REGISTER_LOG.DOC_WEB_URL
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocWebUrl(String docWebUrl) {
        this.docWebUrl = docWebUrl == null ? null : docWebUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.REGISTER_TIME
     *
     * @return the value of R_REGISTER_LOG.REGISTER_TIME
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.REGISTER_TIME
     *
     * @param registerTime the value for R_REGISTER_LOG.REGISTER_TIME
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setRegisterTime(String registerTime) {
        this.registerTime = registerTime == null ? null : registerTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_REGISTER_LOG.DOC_VERSION
     *
     * @return the value of R_REGISTER_LOG.DOC_VERSION
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getDocVersion() {
        return docVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_REGISTER_LOG.DOC_VERSION
     *
     * @param docVersion the value for R_REGISTER_LOG.DOC_VERSION
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDocVersion(String docVersion) {
        this.docVersion = docVersion == null ? null : docVersion.trim();
    }
}