package com.zebone.empi.vo;

import java.util.ArrayList;
import java.util.List;

public class RegisterLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public RegisterLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID_ like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID_ not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMainIdIsNull() {
            addCriterion("MAIN_ID is null");
            return (Criteria) this;
        }

        public Criteria andMainIdIsNotNull() {
            addCriterion("MAIN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMainIdEqualTo(String value) {
            addCriterion("MAIN_ID =", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdNotEqualTo(String value) {
            addCriterion("MAIN_ID <>", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdGreaterThan(String value) {
            addCriterion("MAIN_ID >", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdGreaterThanOrEqualTo(String value) {
            addCriterion("MAIN_ID >=", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdLessThan(String value) {
            addCriterion("MAIN_ID <", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdLessThanOrEqualTo(String value) {
            addCriterion("MAIN_ID <=", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdLike(String value) {
            addCriterion("MAIN_ID like", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdNotLike(String value) {
            addCriterion("MAIN_ID not like", value, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdIn(List<String> values) {
            addCriterion("MAIN_ID in", values, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdNotIn(List<String> values) {
            addCriterion("MAIN_ID not in", values, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdBetween(String value1, String value2) {
            addCriterion("MAIN_ID between", value1, value2, "mainId");
            return (Criteria) this;
        }

        public Criteria andMainIdNotBetween(String value1, String value2) {
            addCriterion("MAIN_ID not between", value1, value2, "mainId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdIsNull() {
            addCriterion("EMPI_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmpiIdIsNotNull() {
            addCriterion("EMPI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmpiIdEqualTo(String value) {
            addCriterion("EMPI_ID =", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdNotEqualTo(String value) {
            addCriterion("EMPI_ID <>", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdGreaterThan(String value) {
            addCriterion("EMPI_ID >", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdGreaterThanOrEqualTo(String value) {
            addCriterion("EMPI_ID >=", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdLessThan(String value) {
            addCriterion("EMPI_ID <", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdLessThanOrEqualTo(String value) {
            addCriterion("EMPI_ID <=", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdLike(String value) {
            addCriterion("EMPI_ID like", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdNotLike(String value) {
            addCriterion("EMPI_ID not like", value, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdIn(List<String> values) {
            addCriterion("EMPI_ID in", values, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdNotIn(List<String> values) {
            addCriterion("EMPI_ID not in", values, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdBetween(String value1, String value2) {
            addCriterion("EMPI_ID between", value1, value2, "empiId");
            return (Criteria) this;
        }

        public Criteria andEmpiIdNotBetween(String value1, String value2) {
            addCriterion("EMPI_ID not between", value1, value2, "empiId");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceIsNull() {
            addCriterion("DOC_DATA_SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceIsNotNull() {
            addCriterion("DOC_DATA_SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceEqualTo(String value) {
            addCriterion("DOC_DATA_SOURCE =", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceNotEqualTo(String value) {
            addCriterion("DOC_DATA_SOURCE <>", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceGreaterThan(String value) {
            addCriterion("DOC_DATA_SOURCE >", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_DATA_SOURCE >=", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceLessThan(String value) {
            addCriterion("DOC_DATA_SOURCE <", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceLessThanOrEqualTo(String value) {
            addCriterion("DOC_DATA_SOURCE <=", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceLike(String value) {
            addCriterion("DOC_DATA_SOURCE like", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceNotLike(String value) {
            addCriterion("DOC_DATA_SOURCE not like", value, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceIn(List<String> values) {
            addCriterion("DOC_DATA_SOURCE in", values, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceNotIn(List<String> values) {
            addCriterion("DOC_DATA_SOURCE not in", values, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceBetween(String value1, String value2) {
            addCriterion("DOC_DATA_SOURCE between", value1, value2, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocDataSourceNotBetween(String value1, String value2) {
            addCriterion("DOC_DATA_SOURCE not between", value1, value2, "docDataSource");
            return (Criteria) this;
        }

        public Criteria andDocOrgIsNull() {
            addCriterion("DOC_ORG is null");
            return (Criteria) this;
        }

        public Criteria andDocOrgIsNotNull() {
            addCriterion("DOC_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andDocOrgEqualTo(String value) {
            addCriterion("DOC_ORG =", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgNotEqualTo(String value) {
            addCriterion("DOC_ORG <>", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgGreaterThan(String value) {
            addCriterion("DOC_ORG >", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_ORG >=", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgLessThan(String value) {
            addCriterion("DOC_ORG <", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgLessThanOrEqualTo(String value) {
            addCriterion("DOC_ORG <=", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgLike(String value) {
            addCriterion("DOC_ORG like", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgNotLike(String value) {
            addCriterion("DOC_ORG not like", value, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgIn(List<String> values) {
            addCriterion("DOC_ORG in", values, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgNotIn(List<String> values) {
            addCriterion("DOC_ORG not in", values, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgBetween(String value1, String value2) {
            addCriterion("DOC_ORG between", value1, value2, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocOrgNotBetween(String value1, String value2) {
            addCriterion("DOC_ORG not between", value1, value2, "docOrg");
            return (Criteria) this;
        }

        public Criteria andDocStateIsNull() {
            addCriterion("DOC_STATE is null");
            return (Criteria) this;
        }

        public Criteria andDocStateIsNotNull() {
            addCriterion("DOC_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andDocStateEqualTo(String value) {
            addCriterion("DOC_STATE =", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateNotEqualTo(String value) {
            addCriterion("DOC_STATE <>", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateGreaterThan(String value) {
            addCriterion("DOC_STATE >", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_STATE >=", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateLessThan(String value) {
            addCriterion("DOC_STATE <", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateLessThanOrEqualTo(String value) {
            addCriterion("DOC_STATE <=", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateLike(String value) {
            addCriterion("DOC_STATE like", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateNotLike(String value) {
            addCriterion("DOC_STATE not like", value, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateIn(List<String> values) {
            addCriterion("DOC_STATE in", values, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateNotIn(List<String> values) {
            addCriterion("DOC_STATE not in", values, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateBetween(String value1, String value2) {
            addCriterion("DOC_STATE between", value1, value2, "docState");
            return (Criteria) this;
        }

        public Criteria andDocStateNotBetween(String value1, String value2) {
            addCriterion("DOC_STATE not between", value1, value2, "docState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateIsNull() {
            addCriterion("DOC_OPER_STATE is null");
            return (Criteria) this;
        }

        public Criteria andDocOperStateIsNotNull() {
            addCriterion("DOC_OPER_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andDocOperStateEqualTo(String value) {
            addCriterion("DOC_OPER_STATE =", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateNotEqualTo(String value) {
            addCriterion("DOC_OPER_STATE <>", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateGreaterThan(String value) {
            addCriterion("DOC_OPER_STATE >", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_OPER_STATE >=", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateLessThan(String value) {
            addCriterion("DOC_OPER_STATE <", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateLessThanOrEqualTo(String value) {
            addCriterion("DOC_OPER_STATE <=", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateLike(String value) {
            addCriterion("DOC_OPER_STATE like", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateNotLike(String value) {
            addCriterion("DOC_OPER_STATE not like", value, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateIn(List<String> values) {
            addCriterion("DOC_OPER_STATE in", values, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateNotIn(List<String> values) {
            addCriterion("DOC_OPER_STATE not in", values, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateBetween(String value1, String value2) {
            addCriterion("DOC_OPER_STATE between", value1, value2, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocOperStateNotBetween(String value1, String value2) {
            addCriterion("DOC_OPER_STATE not between", value1, value2, "docOperState");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeIsNull() {
            addCriterion("DOC_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeIsNotNull() {
            addCriterion("DOC_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeEqualTo(String value) {
            addCriterion("DOC_TYPE_CODE =", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeNotEqualTo(String value) {
            addCriterion("DOC_TYPE_CODE <>", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeGreaterThan(String value) {
            addCriterion("DOC_TYPE_CODE >", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_TYPE_CODE >=", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeLessThan(String value) {
            addCriterion("DOC_TYPE_CODE <", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("DOC_TYPE_CODE <=", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeLike(String value) {
            addCriterion("DOC_TYPE_CODE like", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeNotLike(String value) {
            addCriterion("DOC_TYPE_CODE not like", value, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeIn(List<String> values) {
            addCriterion("DOC_TYPE_CODE in", values, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeNotIn(List<String> values) {
            addCriterion("DOC_TYPE_CODE not in", values, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeBetween(String value1, String value2) {
            addCriterion("DOC_TYPE_CODE between", value1, value2, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocTypeCodeNotBetween(String value1, String value2) {
            addCriterion("DOC_TYPE_CODE not between", value1, value2, "docTypeCode");
            return (Criteria) this;
        }

        public Criteria andDocNoIsNull() {
            addCriterion("DOC_NO is null");
            return (Criteria) this;
        }

        public Criteria andDocNoIsNotNull() {
            addCriterion("DOC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andDocNoEqualTo(String value) {
            addCriterion("DOC_NO =", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoNotEqualTo(String value) {
            addCriterion("DOC_NO <>", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoGreaterThan(String value) {
            addCriterion("DOC_NO >", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_NO >=", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoLessThan(String value) {
            addCriterion("DOC_NO <", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoLessThanOrEqualTo(String value) {
            addCriterion("DOC_NO <=", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoLike(String value) {
            addCriterion("DOC_NO like", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoNotLike(String value) {
            addCriterion("DOC_NO not like", value, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoIn(List<String> values) {
            addCriterion("DOC_NO in", values, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoNotIn(List<String> values) {
            addCriterion("DOC_NO not in", values, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoBetween(String value1, String value2) {
            addCriterion("DOC_NO between", value1, value2, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocNoNotBetween(String value1, String value2) {
            addCriterion("DOC_NO not between", value1, value2, "docNo");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlIsNull() {
            addCriterion("DOC_WEB_URL is null");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlIsNotNull() {
            addCriterion("DOC_WEB_URL is not null");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlEqualTo(String value) {
            addCriterion("DOC_WEB_URL =", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlNotEqualTo(String value) {
            addCriterion("DOC_WEB_URL <>", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlGreaterThan(String value) {
            addCriterion("DOC_WEB_URL >", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_WEB_URL >=", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlLessThan(String value) {
            addCriterion("DOC_WEB_URL <", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlLessThanOrEqualTo(String value) {
            addCriterion("DOC_WEB_URL <=", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlLike(String value) {
            addCriterion("DOC_WEB_URL like", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlNotLike(String value) {
            addCriterion("DOC_WEB_URL not like", value, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlIn(List<String> values) {
            addCriterion("DOC_WEB_URL in", values, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlNotIn(List<String> values) {
            addCriterion("DOC_WEB_URL not in", values, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlBetween(String value1, String value2) {
            addCriterion("DOC_WEB_URL between", value1, value2, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andDocWebUrlNotBetween(String value1, String value2) {
            addCriterion("DOC_WEB_URL not between", value1, value2, "docWebUrl");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("REGISTER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("REGISTER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(String value) {
            addCriterion("REGISTER_TIME =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(String value) {
            addCriterion("REGISTER_TIME <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(String value) {
            addCriterion("REGISTER_TIME >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_TIME >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(String value) {
            addCriterion("REGISTER_TIME <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_TIME <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLike(String value) {
            addCriterion("REGISTER_TIME like", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotLike(String value) {
            addCriterion("REGISTER_TIME not like", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<String> values) {
            addCriterion("REGISTER_TIME in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<String> values) {
            addCriterion("REGISTER_TIME not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(String value1, String value2) {
            addCriterion("REGISTER_TIME between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(String value1, String value2) {
            addCriterion("REGISTER_TIME not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andDocVersionIsNull() {
            addCriterion("DOC_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andDocVersionIsNotNull() {
            addCriterion("DOC_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andDocVersionEqualTo(String value) {
            addCriterion("DOC_VERSION =", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionNotEqualTo(String value) {
            addCriterion("DOC_VERSION <>", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionGreaterThan(String value) {
            addCriterion("DOC_VERSION >", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_VERSION >=", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionLessThan(String value) {
            addCriterion("DOC_VERSION <", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionLessThanOrEqualTo(String value) {
            addCriterion("DOC_VERSION <=", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionLike(String value) {
            addCriterion("DOC_VERSION like", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionNotLike(String value) {
            addCriterion("DOC_VERSION not like", value, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionIn(List<String> values) {
            addCriterion("DOC_VERSION in", values, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionNotIn(List<String> values) {
            addCriterion("DOC_VERSION not in", values, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionBetween(String value1, String value2) {
            addCriterion("DOC_VERSION between", value1, value2, "docVersion");
            return (Criteria) this;
        }

        public Criteria andDocVersionNotBetween(String value1, String value2) {
            addCriterion("DOC_VERSION not between", value1, value2, "docVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 11 14:55:23 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_REGISTER_LOG
     *
     * @mbggenerated Mon Aug 11 14:55:23 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}