package com.zebone.dip.ws.resource.model;

import java.math.BigDecimal;

public class PResourceUserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ID_
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.U_ID
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.NAME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ALIAS
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ID_TYPE_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String idTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ID_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.MEDICAL_ORGAN_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String medicalOrganCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.SEX_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.NATIONALITY_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String nationalityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.NATION_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String nationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.NATIVE_PLACE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.BIRTHDAY
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.MARITAL_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String maritalStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.DEPARTMENT_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.JOB_CATEGORY_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String jobCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.POST_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.POSITIONAL_TITLES_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String positionalTitlesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.POLITICAL_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String politicalStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ADDRESS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String addressCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ADDRESS
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.TEL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.MOBILE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.EMAIL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.QQ
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.MSN
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.ENTRY_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.QUALIFICATION_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String qualificationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.EXAM_SOURCE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private float examSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.CERTIFICATE_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String certificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.SCHOOL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.PROFESSION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.EDUCATION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.DEGREE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.DIPLOMA_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String diplomaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.DEGREE_CERTIFICATE_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String degreeCertificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.GRADUATION_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String graduationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.SCHOOL_SYSTEM
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String schoolSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.HEALTH_CONDITION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String healthCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.FIRST_WORK_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String firstWorkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.RESUME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String resume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.OPER_TYPE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.CREATE_TIME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.INPUT_ORG_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String inputOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_USER_LOG.INPUT_USER_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    private String inputUserCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ID_
     *
     * @return the value of P_RESOURCE_USER_LOG.ID_
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ID_
     *
     * @param id the value for P_RESOURCE_USER_LOG.ID_
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.U_ID
     *
     * @return the value of P_RESOURCE_USER_LOG.U_ID
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.U_ID
     *
     * @param uId the value for P_RESOURCE_USER_LOG.U_ID
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.CODE
     *
     * @param code the value for P_RESOURCE_USER_LOG.CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.NAME
     *
     * @return the value of P_RESOURCE_USER_LOG.NAME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.NAME
     *
     * @param name the value for P_RESOURCE_USER_LOG.NAME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ALIAS
     *
     * @return the value of P_RESOURCE_USER_LOG.ALIAS
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ALIAS
     *
     * @param alias the value for P_RESOURCE_USER_LOG.ALIAS
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ID_TYPE_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.ID_TYPE_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getIdTypeCode() {
        return idTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ID_TYPE_CODE
     *
     * @param idTypeCode the value for P_RESOURCE_USER_LOG.ID_TYPE_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setIdTypeCode(String idTypeCode) {
        this.idTypeCode = idTypeCode == null ? null : idTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ID_NO
     *
     * @return the value of P_RESOURCE_USER_LOG.ID_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ID_NO
     *
     * @param idNo the value for P_RESOURCE_USER_LOG.ID_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.MEDICAL_ORGAN_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.MEDICAL_ORGAN_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getMedicalOrganCode() {
        return medicalOrganCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.MEDICAL_ORGAN_CODE
     *
     * @param medicalOrganCode the value for P_RESOURCE_USER_LOG.MEDICAL_ORGAN_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setMedicalOrganCode(String medicalOrganCode) {
        this.medicalOrganCode = medicalOrganCode == null ? null : medicalOrganCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.SEX_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.SEX_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.SEX_CODE
     *
     * @param sexCode the value for P_RESOURCE_USER_LOG.SEX_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode == null ? null : sexCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.NATIONALITY_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.NATIONALITY_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getNationalityCode() {
        return nationalityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.NATIONALITY_CODE
     *
     * @param nationalityCode the value for P_RESOURCE_USER_LOG.NATIONALITY_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setNationalityCode(String nationalityCode) {
        this.nationalityCode = nationalityCode == null ? null : nationalityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.NATION_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.NATION_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.NATION_CODE
     *
     * @param nationCode the value for P_RESOURCE_USER_LOG.NATION_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.NATIVE_PLACE
     *
     * @return the value of P_RESOURCE_USER_LOG.NATIVE_PLACE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.NATIVE_PLACE
     *
     * @param nativePlace the value for P_RESOURCE_USER_LOG.NATIVE_PLACE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.BIRTHDAY
     *
     * @return the value of P_RESOURCE_USER_LOG.BIRTHDAY
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.BIRTHDAY
     *
     * @param birthday the value for P_RESOURCE_USER_LOG.BIRTHDAY
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.MARITAL_STATUS_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.MARITAL_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getMaritalStatusCode() {
        return maritalStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.MARITAL_STATUS_CODE
     *
     * @param maritalStatusCode the value for P_RESOURCE_USER_LOG.MARITAL_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setMaritalStatusCode(String maritalStatusCode) {
        this.maritalStatusCode = maritalStatusCode == null ? null : maritalStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.DEPARTMENT_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.DEPARTMENT_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.DEPARTMENT_CODE
     *
     * @param departmentCode the value for P_RESOURCE_USER_LOG.DEPARTMENT_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.JOB_CATEGORY_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.JOB_CATEGORY_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getJobCategoryCode() {
        return jobCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.JOB_CATEGORY_CODE
     *
     * @param jobCategoryCode the value for P_RESOURCE_USER_LOG.JOB_CATEGORY_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setJobCategoryCode(String jobCategoryCode) {
        this.jobCategoryCode = jobCategoryCode == null ? null : jobCategoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.POST_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.POST_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.POST_CODE
     *
     * @param postCode the value for P_RESOURCE_USER_LOG.POST_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.POSITIONAL_TITLES_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.POSITIONAL_TITLES_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getPositionalTitlesCode() {
        return positionalTitlesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.POSITIONAL_TITLES_CODE
     *
     * @param positionalTitlesCode the value for P_RESOURCE_USER_LOG.POSITIONAL_TITLES_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setPositionalTitlesCode(String positionalTitlesCode) {
        this.positionalTitlesCode = positionalTitlesCode == null ? null : positionalTitlesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.POLITICAL_STATUS_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.POLITICAL_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getPoliticalStatusCode() {
        return politicalStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.POLITICAL_STATUS_CODE
     *
     * @param politicalStatusCode the value for P_RESOURCE_USER_LOG.POLITICAL_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setPoliticalStatusCode(String politicalStatusCode) {
        this.politicalStatusCode = politicalStatusCode == null ? null : politicalStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ADDRESS_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.ADDRESS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getAddressCode() {
        return addressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ADDRESS_CODE
     *
     * @param addressCode the value for P_RESOURCE_USER_LOG.ADDRESS_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setAddressCode(String addressCode) {
        this.addressCode = addressCode == null ? null : addressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ADDRESS
     *
     * @return the value of P_RESOURCE_USER_LOG.ADDRESS
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ADDRESS
     *
     * @param address the value for P_RESOURCE_USER_LOG.ADDRESS
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.TEL
     *
     * @return the value of P_RESOURCE_USER_LOG.TEL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.TEL
     *
     * @param tel the value for P_RESOURCE_USER_LOG.TEL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.MOBILE
     *
     * @return the value of P_RESOURCE_USER_LOG.MOBILE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.MOBILE
     *
     * @param mobile the value for P_RESOURCE_USER_LOG.MOBILE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.EMAIL
     *
     * @return the value of P_RESOURCE_USER_LOG.EMAIL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.EMAIL
     *
     * @param email the value for P_RESOURCE_USER_LOG.EMAIL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.QQ
     *
     * @return the value of P_RESOURCE_USER_LOG.QQ
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.QQ
     *
     * @param qq the value for P_RESOURCE_USER_LOG.QQ
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.MSN
     *
     * @return the value of P_RESOURCE_USER_LOG.MSN
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.MSN
     *
     * @param msn the value for P_RESOURCE_USER_LOG.MSN
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.ENTRY_DATE
     *
     * @return the value of P_RESOURCE_USER_LOG.ENTRY_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.ENTRY_DATE
     *
     * @param entryDate the value for P_RESOURCE_USER_LOG.ENTRY_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate == null ? null : entryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.QUALIFICATION_DATE
     *
     * @return the value of P_RESOURCE_USER_LOG.QUALIFICATION_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getQualificationDate() {
        return qualificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.QUALIFICATION_DATE
     *
     * @param qualificationDate the value for P_RESOURCE_USER_LOG.QUALIFICATION_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setQualificationDate(String qualificationDate) {
        this.qualificationDate = qualificationDate == null ? null : qualificationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.EXAM_SOURCE
     *
     * @return the value of P_RESOURCE_USER_LOG.EXAM_SOURCE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public float getExamSource() {
        return examSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.EXAM_SOURCE
     *
     * @param examSource the value for P_RESOURCE_USER_LOG.EXAM_SOURCE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setExamSource(float examSource) {
        this.examSource = examSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.CERTIFICATE_NO
     *
     * @return the value of P_RESOURCE_USER_LOG.CERTIFICATE_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.CERTIFICATE_NO
     *
     * @param certificateNo the value for P_RESOURCE_USER_LOG.CERTIFICATE_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo == null ? null : certificateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.SCHOOL
     *
     * @return the value of P_RESOURCE_USER_LOG.SCHOOL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.SCHOOL
     *
     * @param school the value for P_RESOURCE_USER_LOG.SCHOOL
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.PROFESSION
     *
     * @return the value of P_RESOURCE_USER_LOG.PROFESSION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.PROFESSION
     *
     * @param profession the value for P_RESOURCE_USER_LOG.PROFESSION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.EDUCATION
     *
     * @return the value of P_RESOURCE_USER_LOG.EDUCATION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.EDUCATION
     *
     * @param education the value for P_RESOURCE_USER_LOG.EDUCATION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.DEGREE
     *
     * @return the value of P_RESOURCE_USER_LOG.DEGREE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.DEGREE
     *
     * @param degree the value for P_RESOURCE_USER_LOG.DEGREE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.DIPLOMA_NO
     *
     * @return the value of P_RESOURCE_USER_LOG.DIPLOMA_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getDiplomaNo() {
        return diplomaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.DIPLOMA_NO
     *
     * @param diplomaNo the value for P_RESOURCE_USER_LOG.DIPLOMA_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setDiplomaNo(String diplomaNo) {
        this.diplomaNo = diplomaNo == null ? null : diplomaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.DEGREE_CERTIFICATE_NO
     *
     * @return the value of P_RESOURCE_USER_LOG.DEGREE_CERTIFICATE_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getDegreeCertificateNo() {
        return degreeCertificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.DEGREE_CERTIFICATE_NO
     *
     * @param degreeCertificateNo the value for P_RESOURCE_USER_LOG.DEGREE_CERTIFICATE_NO
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setDegreeCertificateNo(String degreeCertificateNo) {
        this.degreeCertificateNo = degreeCertificateNo == null ? null : degreeCertificateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.GRADUATION_DATE
     *
     * @return the value of P_RESOURCE_USER_LOG.GRADUATION_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getGraduationDate() {
        return graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.GRADUATION_DATE
     *
     * @param graduationDate the value for P_RESOURCE_USER_LOG.GRADUATION_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setGraduationDate(String graduationDate) {
        this.graduationDate = graduationDate == null ? null : graduationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.SCHOOL_SYSTEM
     *
     * @return the value of P_RESOURCE_USER_LOG.SCHOOL_SYSTEM
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getSchoolSystem() {
        return schoolSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.SCHOOL_SYSTEM
     *
     * @param schoolSystem the value for P_RESOURCE_USER_LOG.SCHOOL_SYSTEM
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setSchoolSystem(String schoolSystem) {
        this.schoolSystem = schoolSystem == null ? null : schoolSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.HEALTH_CONDITION
     *
     * @return the value of P_RESOURCE_USER_LOG.HEALTH_CONDITION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getHealthCondition() {
        return healthCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.HEALTH_CONDITION
     *
     * @param healthCondition the value for P_RESOURCE_USER_LOG.HEALTH_CONDITION
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setHealthCondition(String healthCondition) {
        this.healthCondition = healthCondition == null ? null : healthCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.FIRST_WORK_DATE
     *
     * @return the value of P_RESOURCE_USER_LOG.FIRST_WORK_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getFirstWorkDate() {
        return firstWorkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.FIRST_WORK_DATE
     *
     * @param firstWorkDate the value for P_RESOURCE_USER_LOG.FIRST_WORK_DATE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setFirstWorkDate(String firstWorkDate) {
        this.firstWorkDate = firstWorkDate == null ? null : firstWorkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.RESUME
     *
     * @return the value of P_RESOURCE_USER_LOG.RESUME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.RESUME
     *
     * @param resume the value for P_RESOURCE_USER_LOG.RESUME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.OPER_TYPE
     *
     * @return the value of P_RESOURCE_USER_LOG.OPER_TYPE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.OPER_TYPE
     *
     * @param operType the value for P_RESOURCE_USER_LOG.OPER_TYPE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.CREATE_TIME
     *
     * @return the value of P_RESOURCE_USER_LOG.CREATE_TIME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.CREATE_TIME
     *
     * @param createTime the value for P_RESOURCE_USER_LOG.CREATE_TIME
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.INPUT_ORG_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.INPUT_ORG_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getInputOrgCode() {
        return inputOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.INPUT_ORG_CODE
     *
     * @param inputOrgCode the value for P_RESOURCE_USER_LOG.INPUT_ORG_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setInputOrgCode(String inputOrgCode) {
        this.inputOrgCode = inputOrgCode == null ? null : inputOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_USER_LOG.INPUT_USER_CODE
     *
     * @return the value of P_RESOURCE_USER_LOG.INPUT_USER_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public String getInputUserCode() {
        return inputUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_USER_LOG.INPUT_USER_CODE
     *
     * @param inputUserCode the value for P_RESOURCE_USER_LOG.INPUT_USER_CODE
     *
     * @mbggenerated Mon Mar 31 08:42:14 CST 2014
     */
    public void setInputUserCode(String inputUserCode) {
        this.inputUserCode = inputUserCode == null ? null : inputUserCode.trim();
    }
}