package com.zebone.dip.ws.resource.model;


public class PResourceFamilyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMI_ID
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String famiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMI_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String famiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.LANDLORD_NAME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String landlordName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.LANDLORD_TEL
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String landlordTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.HOUSEHOLD_NAME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String householdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.HOUSE_POPU_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String housePopuNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.RESIDENT_POPU_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String residentPopuNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.LIVE_TYPE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String liveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.TOTAL_AREA
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String totalArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.PER_AREA
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String perArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_TEL
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.PAPER_FILE_NO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String paperFileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.HOUSING_PROPERTY_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String housingPropertyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.HOUSING_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String housingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.HOUSING_LIGHTING_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String housingLightingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_ORG_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.DOCTOR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_ADDR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyAddrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_ADDR
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.HOUSING_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String housingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.KITCHEN_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String kitchenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.KITCHEN_VENT__CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String kitchenVentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_PRO__CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyProCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.WATER_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String waterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FUEL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String fuelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.TOILETS_TYPE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String toiletsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.LIVESTOCK_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String livestockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.ELEC_DEVICE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String elecDeviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.VEHICLE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String vehicleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.ECON_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String econStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.PER_MONTH_INCOME_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String perMonthIncomeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMI_TOTAL_PAY
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String famiTotalPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMI_FOOD_PAY
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String famiFoodPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.GAR_DISPOSAL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String garDisposalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.SEWAGE_DIPOSAL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String sewageDiposalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.CULT_SPORT_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String cultSportCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FILE_DATE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String fileDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FILE_DOCTOR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String fileDoctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.INPUT_DATE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.INPUT_USER_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String inputUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_TYPE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.FAMILY_MAIN_PROBLEM
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String familyMainProblem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.REMARK
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.USER_ID
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_RESOURCE_FAMILY_INFO.ORG_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    private String orgCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_ID
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMI_ID
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamiId() {
        return famiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_ID
     *
     * @param famiId the value for P_RESOURCE_FAMILY_INFO.FAMI_ID
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamiId(String famiId) {
        this.famiId = famiId == null ? null : famiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMI_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamiCode() {
        return famiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_CODE
     *
     * @param famiCode the value for P_RESOURCE_FAMILY_INFO.FAMI_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamiCode(String famiCode) {
        this.famiCode = famiCode == null ? null : famiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.LANDLORD_NAME
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.LANDLORD_NAME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getLandlordName() {
        return landlordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.LANDLORD_NAME
     *
     * @param landlordName the value for P_RESOURCE_FAMILY_INFO.LANDLORD_NAME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setLandlordName(String landlordName) {
        this.landlordName = landlordName == null ? null : landlordName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.LANDLORD_TEL
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.LANDLORD_TEL
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getLandlordTel() {
        return landlordTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.LANDLORD_TEL
     *
     * @param landlordTel the value for P_RESOURCE_FAMILY_INFO.LANDLORD_TEL
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setLandlordTel(String landlordTel) {
        this.landlordTel = landlordTel == null ? null : landlordTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.HOUSEHOLD_NAME
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.HOUSEHOLD_NAME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getHouseholdName() {
        return householdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.HOUSEHOLD_NAME
     *
     * @param householdName the value for P_RESOURCE_FAMILY_INFO.HOUSEHOLD_NAME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setHouseholdName(String householdName) {
        this.householdName = householdName == null ? null : householdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.HOUSE_POPU_NUMBER
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.HOUSE_POPU_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getHousePopuNumber() {
        return housePopuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.HOUSE_POPU_NUMBER
     *
     * @param housePopuNumber the value for P_RESOURCE_FAMILY_INFO.HOUSE_POPU_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setHousePopuNumber(String housePopuNumber) {
        this.housePopuNumber = housePopuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.RESIDENT_POPU_NUMBER
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.RESIDENT_POPU_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getResidentPopuNumber() {
        return residentPopuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.RESIDENT_POPU_NUMBER
     *
     * @param residentPopuNumber the value for P_RESOURCE_FAMILY_INFO.RESIDENT_POPU_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setResidentPopuNumber(String residentPopuNumber) {
        this.residentPopuNumber = residentPopuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.LIVE_TYPE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.LIVE_TYPE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getLiveType() {
        return liveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.LIVE_TYPE
     *
     * @param liveType the value for P_RESOURCE_FAMILY_INFO.LIVE_TYPE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setLiveType(String liveType) {
        this.liveType = liveType == null ? null : liveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.TOTAL_AREA
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.TOTAL_AREA
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getTotalArea() {
        return totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.TOTAL_AREA
     *
     * @param totalArea the value for P_RESOURCE_FAMILY_INFO.TOTAL_AREA
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setTotalArea(String totalArea) {
        this.totalArea = totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.PER_AREA
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.PER_AREA
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getPerArea() {
        return perArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.PER_AREA
     *
     * @param perArea the value for P_RESOURCE_FAMILY_INFO.PER_AREA
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setPerArea(String perArea) {
        this.perArea = perArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_TEL
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_TEL
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyTel() {
        return familyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_TEL
     *
     * @param familyTel the value for P_RESOURCE_FAMILY_INFO.FAMILY_TEL
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyTel(String familyTel) {
        this.familyTel = familyTel == null ? null : familyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.PAPER_FILE_NO
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.PAPER_FILE_NO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getPaperFileNo() {
        return paperFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.PAPER_FILE_NO
     *
     * @param paperFileNo the value for P_RESOURCE_FAMILY_INFO.PAPER_FILE_NO
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setPaperFileNo(String paperFileNo) {
        this.paperFileNo = paperFileNo == null ? null : paperFileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_PROPERTY_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.HOUSING_PROPERTY_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getHousingPropertyCode() {
        return housingPropertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_PROPERTY_CODE
     *
     * @param housingPropertyCode the value for P_RESOURCE_FAMILY_INFO.HOUSING_PROPERTY_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setHousingPropertyCode(String housingPropertyCode) {
        this.housingPropertyCode = housingPropertyCode == null ? null : housingPropertyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_NUMBER
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.HOUSING_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getHousingNumber() {
        return housingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_NUMBER
     *
     * @param housingNumber the value for P_RESOURCE_FAMILY_INFO.HOUSING_NUMBER
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setHousingNumber(String housingNumber) {
        this.housingNumber = housingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_LIGHTING_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.HOUSING_LIGHTING_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getHousingLightingCode() {
        return housingLightingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_LIGHTING_CODE
     *
     * @param housingLightingCode the value for P_RESOURCE_FAMILY_INFO.HOUSING_LIGHTING_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setHousingLightingCode(String housingLightingCode) {
        this.housingLightingCode = housingLightingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_ORG_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_ORG_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyOrgCode() {
        return familyOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_ORG_CODE
     *
     * @param familyOrgCode the value for P_RESOURCE_FAMILY_INFO.FAMILY_ORG_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyOrgCode(String familyOrgCode) {
        this.familyOrgCode = familyOrgCode == null ? null : familyOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.DOCTOR_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.DOCTOR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.DOCTOR_CODE
     *
     * @param doctorCode the value for P_RESOURCE_FAMILY_INFO.DOCTOR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_ADDR_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_ADDR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyAddrCode() {
        return familyAddrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_ADDR_CODE
     *
     * @param familyAddrCode the value for P_RESOURCE_FAMILY_INFO.FAMILY_ADDR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyAddrCode(String familyAddrCode) {
        this.familyAddrCode = familyAddrCode == null ? null : familyAddrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_ADDR
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_ADDR
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyAddr() {
        return familyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_ADDR
     *
     * @param familyAddr the value for P_RESOURCE_FAMILY_INFO.FAMILY_ADDR
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyAddr(String familyAddr) {
        this.familyAddr = familyAddr == null ? null : familyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.HOUSING_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getHousingCode() {
        return housingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.HOUSING_CODE
     *
     * @param housingCode the value for P_RESOURCE_FAMILY_INFO.HOUSING_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setHousingCode(String housingCode) {
        this.housingCode = housingCode == null ? null : housingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.KITCHEN_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.KITCHEN_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getKitchenCode() {
        return kitchenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.KITCHEN_CODE
     *
     * @param kitchenCode the value for P_RESOURCE_FAMILY_INFO.KITCHEN_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setKitchenCode(String kitchenCode) {
        this.kitchenCode = kitchenCode == null ? null : kitchenCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.KITCHEN_VENT__CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.KITCHEN_VENT__CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getKitchenVentCode() {
        return kitchenVentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.KITCHEN_VENT__CODE
     *
     * @param kitchenVentCode the value for P_RESOURCE_FAMILY_INFO.KITCHEN_VENT__CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setKitchenVentCode(String kitchenVentCode) {
        this.kitchenVentCode = kitchenVentCode == null ? null : kitchenVentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_PRO__CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_PRO__CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyProCode() {
        return familyProCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_PRO__CODE
     *
     * @param familyProCode the value for P_RESOURCE_FAMILY_INFO.FAMILY_PRO__CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyProCode(String familyProCode) {
        this.familyProCode = familyProCode == null ? null : familyProCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.WATER_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.WATER_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getWaterCode() {
        return waterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.WATER_CODE
     *
     * @param waterCode the value for P_RESOURCE_FAMILY_INFO.WATER_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setWaterCode(String waterCode) {
        this.waterCode = waterCode == null ? null : waterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FUEL_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FUEL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFuelCode() {
        return fuelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FUEL_CODE
     *
     * @param fuelCode the value for P_RESOURCE_FAMILY_INFO.FUEL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFuelCode(String fuelCode) {
        this.fuelCode = fuelCode == null ? null : fuelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.TOILETS_TYPE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.TOILETS_TYPE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getToiletsType() {
        return toiletsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.TOILETS_TYPE
     *
     * @param toiletsType the value for P_RESOURCE_FAMILY_INFO.TOILETS_TYPE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setToiletsType(String toiletsType) {
        this.toiletsType = toiletsType == null ? null : toiletsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.LIVESTOCK_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.LIVESTOCK_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getLivestockCode() {
        return livestockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.LIVESTOCK_CODE
     *
     * @param livestockCode the value for P_RESOURCE_FAMILY_INFO.LIVESTOCK_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setLivestockCode(String livestockCode) {
        this.livestockCode = livestockCode == null ? null : livestockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.ELEC_DEVICE_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.ELEC_DEVICE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getElecDeviceCode() {
        return elecDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.ELEC_DEVICE_CODE
     *
     * @param elecDeviceCode the value for P_RESOURCE_FAMILY_INFO.ELEC_DEVICE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setElecDeviceCode(String elecDeviceCode) {
        this.elecDeviceCode = elecDeviceCode == null ? null : elecDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.VEHICLE_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.VEHICLE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getVehicleCode() {
        return vehicleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.VEHICLE_CODE
     *
     * @param vehicleCode the value for P_RESOURCE_FAMILY_INFO.VEHICLE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setVehicleCode(String vehicleCode) {
        this.vehicleCode = vehicleCode == null ? null : vehicleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.ECON_STATUS_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.ECON_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getEconStatusCode() {
        return econStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.ECON_STATUS_CODE
     *
     * @param econStatusCode the value for P_RESOURCE_FAMILY_INFO.ECON_STATUS_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setEconStatusCode(String econStatusCode) {
        this.econStatusCode = econStatusCode == null ? null : econStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.PER_MONTH_INCOME_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.PER_MONTH_INCOME_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getPerMonthIncomeCode() {
        return perMonthIncomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.PER_MONTH_INCOME_CODE
     *
     * @param perMonthIncomeCode the value for P_RESOURCE_FAMILY_INFO.PER_MONTH_INCOME_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setPerMonthIncomeCode(String perMonthIncomeCode) {
        this.perMonthIncomeCode = perMonthIncomeCode == null ? null : perMonthIncomeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_TOTAL_PAY
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMI_TOTAL_PAY
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamiTotalPay() {
        return famiTotalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_TOTAL_PAY
     *
     * @param famiTotalPay the value for P_RESOURCE_FAMILY_INFO.FAMI_TOTAL_PAY
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamiTotalPay(String famiTotalPay) {
        this.famiTotalPay = famiTotalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_FOOD_PAY
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMI_FOOD_PAY
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamiFoodPay() {
        return famiFoodPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMI_FOOD_PAY
     *
     * @param famiFoodPay the value for P_RESOURCE_FAMILY_INFO.FAMI_FOOD_PAY
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamiFoodPay(String famiFoodPay) {
        this.famiFoodPay = famiFoodPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.GAR_DISPOSAL_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.GAR_DISPOSAL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getGarDisposalCode() {
        return garDisposalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.GAR_DISPOSAL_CODE
     *
     * @param garDisposalCode the value for P_RESOURCE_FAMILY_INFO.GAR_DISPOSAL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setGarDisposalCode(String garDisposalCode) {
        this.garDisposalCode = garDisposalCode == null ? null : garDisposalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.SEWAGE_DIPOSAL_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.SEWAGE_DIPOSAL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getSewageDiposalCode() {
        return sewageDiposalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.SEWAGE_DIPOSAL_CODE
     *
     * @param sewageDiposalCode the value for P_RESOURCE_FAMILY_INFO.SEWAGE_DIPOSAL_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setSewageDiposalCode(String sewageDiposalCode) {
        this.sewageDiposalCode = sewageDiposalCode == null ? null : sewageDiposalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.CULT_SPORT_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.CULT_SPORT_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getCultSportCode() {
        return cultSportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.CULT_SPORT_CODE
     *
     * @param cultSportCode the value for P_RESOURCE_FAMILY_INFO.CULT_SPORT_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setCultSportCode(String cultSportCode) {
        this.cultSportCode = cultSportCode == null ? null : cultSportCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FILE_DATE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FILE_DATE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFileDate() {
        return fileDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FILE_DATE
     *
     * @param fileDate the value for P_RESOURCE_FAMILY_INFO.FILE_DATE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFileDate(String fileDate) {
        this.fileDate = fileDate == null ? null : fileDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FILE_DOCTOR_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FILE_DOCTOR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFileDoctorCode() {
        return fileDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FILE_DOCTOR_CODE
     *
     * @param fileDoctorCode the value for P_RESOURCE_FAMILY_INFO.FILE_DOCTOR_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFileDoctorCode(String fileDoctorCode) {
        this.fileDoctorCode = fileDoctorCode == null ? null : fileDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.INPUT_DATE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.INPUT_DATE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.INPUT_DATE
     *
     * @param inputDate the value for P_RESOURCE_FAMILY_INFO.INPUT_DATE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.INPUT_USER_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.INPUT_USER_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getInputUserCode() {
        return inputUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.INPUT_USER_CODE
     *
     * @param inputUserCode the value for P_RESOURCE_FAMILY_INFO.INPUT_USER_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setInputUserCode(String inputUserCode) {
        this.inputUserCode = inputUserCode == null ? null : inputUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_TYPE_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_TYPE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyTypeCode() {
        return familyTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_TYPE_CODE
     *
     * @param familyTypeCode the value for P_RESOURCE_FAMILY_INFO.FAMILY_TYPE_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyTypeCode(String familyTypeCode) {
        this.familyTypeCode = familyTypeCode == null ? null : familyTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_MAIN_PROBLEM
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.FAMILY_MAIN_PROBLEM
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getFamilyMainProblem() {
        return familyMainProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.FAMILY_MAIN_PROBLEM
     *
     * @param familyMainProblem the value for P_RESOURCE_FAMILY_INFO.FAMILY_MAIN_PROBLEM
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setFamilyMainProblem(String familyMainProblem) {
        this.familyMainProblem = familyMainProblem == null ? null : familyMainProblem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.REMARK
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.REMARK
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.REMARK
     *
     * @param remark the value for P_RESOURCE_FAMILY_INFO.REMARK
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.CREATE_TIME
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.CREATE_TIME
     *
     * @param createTime the value for P_RESOURCE_FAMILY_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.USER_ID
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.USER_ID
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.USER_ID
     *
     * @param userId the value for P_RESOURCE_FAMILY_INFO.USER_ID
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_RESOURCE_FAMILY_INFO.ORG_CODE
     *
     * @return the value of P_RESOURCE_FAMILY_INFO.ORG_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_RESOURCE_FAMILY_INFO.ORG_CODE
     *
     * @param orgCode the value for P_RESOURCE_FAMILY_INFO.ORG_CODE
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }
}