package com.zebone.dip.ws.resource.model;

import java.util.ArrayList;
import java.util.List;

public class PResourceFamilyMembersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public PResourceFamilyMembersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID_ like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID_ not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFamiIdIsNull() {
            addCriterion("FAMI_ID is null");
            return (Criteria) this;
        }

        public Criteria andFamiIdIsNotNull() {
            addCriterion("FAMI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFamiIdEqualTo(String value) {
            addCriterion("FAMI_ID =", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdNotEqualTo(String value) {
            addCriterion("FAMI_ID <>", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdGreaterThan(String value) {
            addCriterion("FAMI_ID >", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdGreaterThanOrEqualTo(String value) {
            addCriterion("FAMI_ID >=", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdLessThan(String value) {
            addCriterion("FAMI_ID <", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdLessThanOrEqualTo(String value) {
            addCriterion("FAMI_ID <=", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdLike(String value) {
            addCriterion("FAMI_ID like", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdNotLike(String value) {
            addCriterion("FAMI_ID not like", value, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdIn(List<String> values) {
            addCriterion("FAMI_ID in", values, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdNotIn(List<String> values) {
            addCriterion("FAMI_ID not in", values, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdBetween(String value1, String value2) {
            addCriterion("FAMI_ID between", value1, value2, "famiId");
            return (Criteria) this;
        }

        public Criteria andFamiIdNotBetween(String value1, String value2) {
            addCriterion("FAMI_ID not between", value1, value2, "famiId");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNull() {
            addCriterion("ORDER_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNotNull() {
            addCriterion("ORDER_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberEqualTo(int value) {
            addCriterion("ORDER_NUMBER =", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotEqualTo(int value) {
            addCriterion("ORDER_NUMBER <>", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThan(int value) {
            addCriterion("ORDER_NUMBER >", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThanOrEqualTo(int value) {
            addCriterion("ORDER_NUMBER >=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThan(int value) {
            addCriterion("ORDER_NUMBER <", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThanOrEqualTo(int value) {
            addCriterion("ORDER_NUMBER <=", value, "orderNumber");
            return (Criteria) this;
        }

//        public Criteria andOrderNumberIn(List<int> values) {
//            addCriterion("ORDER_NUMBER in", values, "orderNumber");
//            return (Criteria) this;
//        }
//
//        public Criteria andOrderNumberNotIn(List<int> values) {
//            addCriterion("ORDER_NUMBER not in", values, "orderNumber");
//            return (Criteria) this;
//        }

        public Criteria andOrderNumberBetween(int value1, int value2) {
            addCriterion("ORDER_NUMBER between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotBetween(int value1, int value2) {
            addCriterion("ORDER_NUMBER not between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeIsNull() {
            addCriterion("HOUSEHOLD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeIsNotNull() {
            addCriterion("HOUSEHOLD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeEqualTo(String value) {
            addCriterion("HOUSEHOLD_CODE =", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeNotEqualTo(String value) {
            addCriterion("HOUSEHOLD_CODE <>", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeGreaterThan(String value) {
            addCriterion("HOUSEHOLD_CODE >", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSEHOLD_CODE >=", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeLessThan(String value) {
            addCriterion("HOUSEHOLD_CODE <", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeLessThanOrEqualTo(String value) {
            addCriterion("HOUSEHOLD_CODE <=", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeLike(String value) {
            addCriterion("HOUSEHOLD_CODE like", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeNotLike(String value) {
            addCriterion("HOUSEHOLD_CODE not like", value, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeIn(List<String> values) {
            addCriterion("HOUSEHOLD_CODE in", values, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeNotIn(List<String> values) {
            addCriterion("HOUSEHOLD_CODE not in", values, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeBetween(String value1, String value2) {
            addCriterion("HOUSEHOLD_CODE between", value1, value2, "householdCode");
            return (Criteria) this;
        }

        public Criteria andHouseholdCodeNotBetween(String value1, String value2) {
            addCriterion("HOUSEHOLD_CODE not between", value1, value2, "householdCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeIsNull() {
            addCriterion("IDCARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeIsNotNull() {
            addCriterion("IDCARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeEqualTo(String value) {
            addCriterion("IDCARD_TYPE =", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeNotEqualTo(String value) {
            addCriterion("IDCARD_TYPE <>", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeGreaterThan(String value) {
            addCriterion("IDCARD_TYPE >", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("IDCARD_TYPE >=", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeLessThan(String value) {
            addCriterion("IDCARD_TYPE <", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeLessThanOrEqualTo(String value) {
            addCriterion("IDCARD_TYPE <=", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeLike(String value) {
            addCriterion("IDCARD_TYPE like", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeNotLike(String value) {
            addCriterion("IDCARD_TYPE not like", value, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeIn(List<String> values) {
            addCriterion("IDCARD_TYPE in", values, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeNotIn(List<String> values) {
            addCriterion("IDCARD_TYPE not in", values, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeBetween(String value1, String value2) {
            addCriterion("IDCARD_TYPE between", value1, value2, "idcardType");
            return (Criteria) this;
        }

        public Criteria andIdcardTypeNotBetween(String value1, String value2) {
            addCriterion("IDCARD_TYPE not between", value1, value2, "idcardType");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("CARD_NO =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("CARD_NO <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("CARD_NO >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NO >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("CARD_NO <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("CARD_NO <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("CARD_NO like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("CARD_NO not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("CARD_NO in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("CARD_NO not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("CARD_NO between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("CARD_NO not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthDateIsNull() {
            addCriterion("BIRTH_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBirthDateIsNotNull() {
            addCriterion("BIRTH_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBirthDateEqualTo(String value) {
            addCriterion("BIRTH_DATE =", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotEqualTo(String value) {
            addCriterion("BIRTH_DATE <>", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateGreaterThan(String value) {
            addCriterion("BIRTH_DATE >", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTH_DATE >=", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLessThan(String value) {
            addCriterion("BIRTH_DATE <", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLessThanOrEqualTo(String value) {
            addCriterion("BIRTH_DATE <=", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLike(String value) {
            addCriterion("BIRTH_DATE like", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotLike(String value) {
            addCriterion("BIRTH_DATE not like", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateIn(List<String> values) {
            addCriterion("BIRTH_DATE in", values, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotIn(List<String> values) {
            addCriterion("BIRTH_DATE not in", values, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateBetween(String value1, String value2) {
            addCriterion("BIRTH_DATE between", value1, value2, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotBetween(String value1, String value2) {
            addCriterion("BIRTH_DATE not between", value1, value2, "birthDate");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeIsNull() {
            addCriterion("EDUCATION_DEGREE is null");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeIsNotNull() {
            addCriterion("EDUCATION_DEGREE is not null");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeEqualTo(String value) {
            addCriterion("EDUCATION_DEGREE =", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotEqualTo(String value) {
            addCriterion("EDUCATION_DEGREE <>", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeGreaterThan(String value) {
            addCriterion("EDUCATION_DEGREE >", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("EDUCATION_DEGREE >=", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeLessThan(String value) {
            addCriterion("EDUCATION_DEGREE <", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeLessThanOrEqualTo(String value) {
            addCriterion("EDUCATION_DEGREE <=", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeLike(String value) {
            addCriterion("EDUCATION_DEGREE like", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotLike(String value) {
            addCriterion("EDUCATION_DEGREE not like", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeIn(List<String> values) {
            addCriterion("EDUCATION_DEGREE in", values, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotIn(List<String> values) {
            addCriterion("EDUCATION_DEGREE not in", values, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeBetween(String value1, String value2) {
            addCriterion("EDUCATION_DEGREE between", value1, value2, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotBetween(String value1, String value2) {
            addCriterion("EDUCATION_DEGREE not between", value1, value2, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andCareerCodeIsNull() {
            addCriterion("CAREER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCareerCodeIsNotNull() {
            addCriterion("CAREER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCareerCodeEqualTo(String value) {
            addCriterion("CAREER_CODE =", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeNotEqualTo(String value) {
            addCriterion("CAREER_CODE <>", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeGreaterThan(String value) {
            addCriterion("CAREER_CODE >", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CAREER_CODE >=", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeLessThan(String value) {
            addCriterion("CAREER_CODE <", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeLessThanOrEqualTo(String value) {
            addCriterion("CAREER_CODE <=", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeLike(String value) {
            addCriterion("CAREER_CODE like", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeNotLike(String value) {
            addCriterion("CAREER_CODE not like", value, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeIn(List<String> values) {
            addCriterion("CAREER_CODE in", values, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeNotIn(List<String> values) {
            addCriterion("CAREER_CODE not in", values, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeBetween(String value1, String value2) {
            addCriterion("CAREER_CODE between", value1, value2, "careerCode");
            return (Criteria) this;
        }

        public Criteria andCareerCodeNotBetween(String value1, String value2) {
            addCriterion("CAREER_CODE not between", value1, value2, "careerCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeIsNull() {
            addCriterion("MARRIAGE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeIsNotNull() {
            addCriterion("MARRIAGE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeEqualTo(String value) {
            addCriterion("MARRIAGE_CODE =", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeNotEqualTo(String value) {
            addCriterion("MARRIAGE_CODE <>", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeGreaterThan(String value) {
            addCriterion("MARRIAGE_CODE >", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MARRIAGE_CODE >=", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeLessThan(String value) {
            addCriterion("MARRIAGE_CODE <", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeLessThanOrEqualTo(String value) {
            addCriterion("MARRIAGE_CODE <=", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeLike(String value) {
            addCriterion("MARRIAGE_CODE like", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeNotLike(String value) {
            addCriterion("MARRIAGE_CODE not like", value, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeIn(List<String> values) {
            addCriterion("MARRIAGE_CODE in", values, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeNotIn(List<String> values) {
            addCriterion("MARRIAGE_CODE not in", values, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeBetween(String value1, String value2) {
            addCriterion("MARRIAGE_CODE between", value1, value2, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andMarriageCodeNotBetween(String value1, String value2) {
            addCriterion("MARRIAGE_CODE not between", value1, value2, "marriageCode");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andFamiNoIsNull() {
            addCriterion("FAMI_NO is null");
            return (Criteria) this;
        }

        public Criteria andFamiNoIsNotNull() {
            addCriterion("FAMI_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFamiNoEqualTo(String value) {
            addCriterion("FAMI_NO =", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoNotEqualTo(String value) {
            addCriterion("FAMI_NO <>", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoGreaterThan(String value) {
            addCriterion("FAMI_NO >", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoGreaterThanOrEqualTo(String value) {
            addCriterion("FAMI_NO >=", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoLessThan(String value) {
            addCriterion("FAMI_NO <", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoLessThanOrEqualTo(String value) {
            addCriterion("FAMI_NO <=", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoLike(String value) {
            addCriterion("FAMI_NO like", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoNotLike(String value) {
            addCriterion("FAMI_NO not like", value, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoIn(List<String> values) {
            addCriterion("FAMI_NO in", values, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoNotIn(List<String> values) {
            addCriterion("FAMI_NO not in", values, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoBetween(String value1, String value2) {
            addCriterion("FAMI_NO between", value1, value2, "famiNo");
            return (Criteria) this;
        }

        public Criteria andFamiNoNotBetween(String value1, String value2) {
            addCriterion("FAMI_NO not between", value1, value2, "famiNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 31 09:06:58 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_RESOURCE_FAMILY_MEMBERS
     *
     * @mbggenerated Mon Mar 31 09:06:58 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}